Entities/Endereco.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppCadastro.Entities
{
    public class Endereco
    {
        public int Id { get; set; }
        public string Logradouro { get; set; }
        public int Numero { get; set; }
        public int Cep { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
    }
}

Entities/Telefone.cs
using AppCadastro.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppCadastro.Entities
{
    public class Telefone
    {

        public int Id { get; set; }
        public int Ddd { get; set; }
        public int Numero { get; set; }

        public virtual TipoTelefone Tipo { get; set; }

        public int PessoaId { get; set; }
        public virtual Pessoa Pessoa { get; set; }
    }
}

Entities/TipoTelefone.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppCadastro.Entities
{
    public class TipoTelefone
    {
        public int Id { get; set; }
        public string Tipo { get; set; }

        public int TelefoneId { get; set; }
        public virtual Telefone Telefone { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace AppCadastro.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using AppCadastro.Entities;

namespace AppCadastro.Models
{
    public class Pessoa
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public long Cpf { get; set; }

        public virtual Endereco Endereco { get; set; }
        public virtual Telefone Telefone { get; set; }


    }
}

Controllers/HomeController.cs
using AppCadastro.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AppCadastro.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }    

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PessoasController.cs
using AppCadastro.Models;
using AppCadastro.Repositories;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppCadastro.Controllers
{
    public class PessoasController : Controller
    {
        private readonly IPessoaDAO _pessoaDAO;
        public PessoasController(IPessoaDAO pessoaDAO)
        {
            _pessoaDAO = pessoaDAO;
        }

        public static List<Pessoa> lsPessoas = new List<Pessoa>();
        public IActionResult Index()
        {
            List<Pessoa> lsPessoas = _pessoaDAO.BuscarTodos();
            return View(lsPessoas);
        }

        public IActionResult Create()
        {               
            return View();
        }

        [HttpPost]
        public IActionResult Create(Pessoa objeto)
        {
            _pessoaDAO.Adicionar(objeto);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {

            Pessoa pessoa = _pessoaDAO.GetById(id);
            return View(pessoa);
        }

        [HttpPost]
        public IActionResult Edit(Pessoa objeto)
        {
            _pessoaDAO.Atualizar(objeto);
            return RedirectToAction("Index");
        }


        public IActionResult Delete(int id)
        {
            _pessoaDAO.Excluir(id);
            return RedirectToAction("Index");
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}           
 

<h4>Página Inicial</h4>

Views/Pessoas/Create.cshtml
@model AppCadastro.Models.Pessoa


@{
    ViewData["Title"] = "Create";
}

<h1>Adicionar</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div>

                <div asp-validation-summary="ModelOnly" ></div>
                <div class="form-group">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Cpf" class="control-label"></label>
                    <input asp-for="Cpf" class="form-control" />
                    <span asp-validation-for="Cpf" class="text-danger"></span>
                </div>
             </div>

             <div >
                        <h6>Endereço:</h6>

                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Endereco.Logradouro" class="control-label"></label>
                            <input asp-for="Endereco.Logradouro" class="form-control" />
                            <span asp-validation-for="Endereco.Logradouro" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Endereco.Numero" class="control-label"></label>
                            <input asp-for="Endereco.Numero" class="form-control" />
                            <span asp-validation-for="Endereco.Numero" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Endereco.Cep" class="control-label"></label>
                            <input asp-for="Endereco.Cep" class="form-control" />
                            <span asp-validation-for="Endereco.Cep" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Endereco.Bairro" class="control-label"></label>
                            <input asp-for="Endereco.Bairro" class="form-control" />
                            <span asp-validation-for="Endereco.Bairro" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Endereco.Cidade" class="control-label"></label>
                            <input asp-for="Endereco.Cidade" class="form-control" />
                            <span asp-validation-for="Endereco.Cidade" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Endereco.Estado" class="control-label"></label>
                            <input asp-for="Endereco.Estado" class="form-control" />
                            <span asp-validation-for="Endereco.Estado" class="text-danger"></span>
                        </div>

                    </div>

                    <div>

                        <h6>Telefone:</h6>
                        <div class="form-group">
                            <label asp-for="Telefone.Ddd" class="control-label"></label>
                            <input asp-for="Telefone.Ddd" class="form-control" />
                            <span asp-validation-for="Telefone.Ddd" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Telefone.Numero" class="control-label"></label>
                            <input asp-for="Telefone.Numero" class="form-control" />
                            <span asp-validation-for="Telefone.Numero" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Telefone.Tipo.Tipo" class="control-label"></label>
                            <input asp-for="Telefone.Tipo.Tipo" class="form-control" />
                            <span asp-validation-for="Telefone.Tipo.Tipo" class="text-danger"></span>
                        </div>

                        <div class="form-group">
                            <input type="submit" value="Adicionar" class="btn btn-primary" />
                        </div>
                    </div>
</form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar a lista de pessoas</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pessoas/Edit.cshtml
@model AppCadastro.Models.Pessoa

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div>

                <div asp-validation-summary="ModelOnly"></div>
                <div class="form-group">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Cpf" class="control-label"></label>
                    <input asp-for="Cpf" class="form-control" />
                    <span asp-validation-for="Cpf" class="text-danger"></span>
                </div>
            </div>

            <div>
                <h6>Endereço:</h6>

                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Endereco.Logradouro" class="control-label"></label>
                    <input asp-for="Endereco.Logradouro" class="form-control" />
                    <span asp-validation-for="Endereco.Logradouro" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Endereco.Numero" class="control-label"></label>
                    <input asp-for="Endereco.Numero" class="form-control" />
                    <span asp-validation-for="Endereco.Numero" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Endereco.Cep" class="control-label"></label>
                    <input asp-for="Endereco.Cep" class="form-control" />
                    <span asp-validation-for="Endereco.Cep" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Endereco.Bairro" class="control-label"></label>
                    <input asp-for="Endereco.Bairro" class="form-control" />
                    <span asp-validation-for="Endereco.Bairro" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Endereco.Cidade" class="control-label"></label>
                    <input asp-for="Endereco.Cidade" class="form-control" />
                    <span asp-validation-for="Endereco.Cidade" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Endereco.Estado" class="control-label"></label>
                    <input asp-for="Endereco.Estado" class="form-control" />
                    <span asp-validation-for="Endereco.Estado" class="text-danger"></span>
                </div>

            </div>

            <div>

                <h6>Telefone:</h6>
                <div class="form-group">
                    <label asp-for="Telefone.Ddd" class="control-label"></label>
                    <input asp-for="Telefone.Ddd" class="form-control" />
                    <span asp-validation-for="Telefone.Ddd" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Telefone.Numero" class="control-label"></label>
                    <input asp-for="Telefone.Numero" class="form-control" />
                    <span asp-validation-for="Telefone.Numero" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Telefone.Tipo.Tipo" class="control-label"></label>
                    <input asp-for="Telefone.Tipo.Tipo" class="form-control" />
                    <span asp-validation-for="Telefone.Tipo.Tipo" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <input type="submit" value="Atualizar" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Retornar a lista de pessoas</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pessoas/Index.cshtml
@model IEnumerable<AppCadastro.Models.Pessoa>

@{
    ViewData["Title"] = "Index";
}

<h1>Lista de Pessoas cadastradas:</h1>

<p>
    <a asp-action="Create">Adicionar nova Pessoa</a>
</p>

@foreach (var item in Model)
{
    <div class="card">
        <div class="card-header">
            <h6>@Html.DisplayFor(modelItem => item.Nome)</h6>
        </div>
        <div class="card-body">
            <h6 class="card-title">
                CPF =@Html.DisplayFor(modelItem => item.Cpf)
            </h6>
            <h6 class="card-text">
                Endereço:
                @Html.DisplayFor(modelItem => item.Endereco.Logradouro),
                @Html.DisplayFor(modelItem => item.Endereco.Numero)
            </h6>
            <h6 class="card-text">
                Cidade: @Html.DisplayFor(modelItem => item.Endereco.Cidade),
                @Html.DisplayFor(modelItem => item.Endereco.Estado)
            </h6>
            <h6 class="card-text">
                CEP: @Html.DisplayFor(modelItem => item.Endereco.Cep)
            </h6>
            <h6 class="card-text">
                Telefone:
                @Html.DisplayFor(modelItem => item.Telefone.Ddd)
                @Html.DisplayFor(modelItem => item.Telefone.Numero)
                Tipo: @Html.DisplayFor(modelItem => item.Telefone.Tipo.Tipo)
            </h6>
            <a class="btn btn-primary" asp-route-id="@item.Id" asp-action="Edit">Editar</a>
            <a class="btn btn-primary" asp-route-id="@item.Id" asp-action="Delete">Excluir</a>
        </div>
    </div>
    <br />
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppCadastro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppCadastro</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>         
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoas" asp-action="Index">Lista de Pessoas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AppCadastro
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>